services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=cyfer_db
      - MARIADB_USER=cyfer_db_user
      - MARIADB_PASSWORD=password
    volumes:
      - type: bind
        source: ./db
        target: /docker-entrypoint-initdb.d
  cyfer:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
     - "80:80"